### ISSUE TITLE
More Language Options Required

### ISSUE THREAD

**Issue by excalith** [excalith/git-cheats#4]
Currently, json file has only English and Turkish localizations. We can add more languages to help people get used to git commands even easier! It is simple enough to localize, you only need to modify **commands.json** file with your translations adding **"lang key": "lang description"** in required fields and it will automatically pop-up in page.

**Comment by kanna6501** [comment]
Working on 2 languages: "Telugu" and "Hindi"

**Comment by excalith** [comment]
Hey @kanna6501 thanks mate! I will also add browser language detection if no cookies are set.

**Comment by MozyOk** [comment]
Hi @excalith 👋
I'll try to add Japanese, ok?

**Comment by excalith** [comment]
Hey @MozyOk 👋
Thanks for your contribution, will be looking forward to see Japanese!

**Comment by aladhims** [comment]
Hi @excalith, can I add Indonesian language?

**Comment by excalith** [comment]
> Hi @excalith, can I add Indonesian language?

@aladhims sure you can mate!

**Comment by aladhims** [comment]
Hi @excalith  I have added support for Indonesian language in [this PR](https://github.com/excalith/git-cheats/pull/13), could you please review it?

**Comment by inhyechoi** [comment]
Hi @excalith, can I add Korean as well?

**Comment by excalith** [comment]
@inhyechoi sure!

**Comment by osamagoraya** [comment]
hi @excalith I am adding Urdu language.

**Comment by Moonstroke82** [comment]
Hi @excalith adding german

**Comment by excalith** [comment]
@osamagoraya had to close your multiple PR's, can you please send one PR with all changes within - not step by step. By the way, I have merged German PR, it would be nice to pull master before applying your changes.

@Moonstroke82 merged your PR, and fixed a few JSON issues. There are also a few sections are not translated. Can you please send another PR with missing translations?

**Comment by Maluzzz** [comment]
Spanish! :)

**Comment by excalith** [comment]
@Maluzzz thanks! And happy hacktoberfest to you too!

**Comment by bhabermann** [comment]
I'll start working on Portuguese (pt-BR) translation

**Comment by munex-com** [comment]
Hi @excalith.  It seems that Japanese isn't added from the last year. 
I added Japanese translation. #21

**Comment by excalith** [comment]
@munex-com thanks mate, merged Japanese
